# IP addresses used by VPN
[ip]
src="10.7.0.4"
dst="10.7.0.1"

# If CPU isolation is used
# Core number don't matter if no isolation
[isolation]
priority=99
isolate_send=false 
core_send=0
isolate_receive=false
core_receive=1

[interface]
input='ens38'
output='ens39'

#Other parameters
[general]
rate=100.0 #Mbps
sending_time=10.0 #In sec
save=true
send=true
receive=false
log=false
dataset=''

